name: hello-world
#when to run the workflow - when we commmit
on: push
jobs: 
  hello-world-job:
  #specify a runner, a machine to run any processes
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "$(cat hello_world.txt)"
